### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by bdvir** [CodinGame/codingame-sdk-modules#1]
I tried using the modules but couldn't due to incomplete documentation.

For example, the [following line](https://github.com/CodinGame/codingame-sdk-modules/blob/b5137d295f5f9f1d900b86b1dc349791d8b0f2d0/src/main/resources/view/modules/endscreen/EndScreenModule.js#L198) mentions a file ('assets/title_ranking.png') which is not already in this repository and is not mentioned in the documentation. 

I also get the following error in chrome:
`TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
 /modules/tooltip/TooltipModule.js:119`

If we can get a more complete documentation or at least a complete runnable example of using each it would be helpful.

BTW, instead of writing it twice, I suggest writing the documentation in:
https://github.com/CodinGame/codingame-sdk-playground/tree/master/extensions
and put a link to the [playground](https://tech.io/playgrounds/25775/codingame-sdk-documentation/introduction-4) in the README.md of this repository.

**Comment by Empheon** [comment]
Thanks for your feedback, I've updated this repo and the documentation accordingly.

I also fixed the Tooltip module, your error should be gone if you use the new version

**Comment by bdvir** [comment]
Thanks @Empheon, but I still get error, now it's (in chrome, again):  
  
```
TypeError: Cannot read property '0' of undefined
    at EndScreenModule.createEndScene (EndScreenModule.js:208)
    at EndScreenModule.reinitScene (EndScreenModule.js:39)
    at Drawer.initScene (Drawer.js:401)
    at Drawer.reinitScene (Drawer.js:529)
    at Drawer.reinit (Drawer.js:557)
    at Drawer.init (Drawer.js:833)
    at g.init (player.js:83)
    at Object.s.resize (player.js:83)
    at checkSize (app.js:141)
    at y (player.js:53)
```
  
I have the `EndScreenModule.js` and `title_ranking.png` files in their folders, modified `config.js` and [set the module's score property](https://tech.io/playgrounds/25775/codingame-sdk-documentation/end-screen-module) as documented.  

I have the `EndScreenModule.java` file in `src\main\java\com\codingame\view\endscreen` (not as documented), as implied by the package line in that file.

**Comment by Empheon** [comment]
Can you try again after adding `this.scores = []` to the constructor of `EndScreenModule.js` ?

**Comment by bdvir** [comment]
Finally it's working locally!

I'm not sure if I should report that here (if not, where?) but when I upload my exported project to CG servers I get the following error:

```
ERROR in ./EndScreenModule.js
Module not found: Error: Can't resolve '../../core/constants.js' in '/tmp/codingame'
 @ ./EndScreenModule.js 10:17-51
 @ ./config.js
 @ ./core/Drawer.js

ERROR in ./EndScreenModule.js
Module not found: Error: Can't resolve '../../core/utils.js' in '/tmp/codingame'
 @ ./EndScreenModule.js 12:13-43
 @ ./config.js
 @ ./core/Drawer.js
```

**Comment by Empheon** [comment]
Great!

The error comes from the fact that this file was formerly in a sub-directory. You can fix that by changing the paths to `./core/constants.js` and `./core/utils.js`.

**Comment by bdvir** [comment]
Working great on CG servers as well, thanks!

Don't forget to commit the `this.scores = []` change.
